### ISSUE TITLE
msk reports auth fail but didnt

### ISSUE THREAD

**Issue by JayKayy** [MycroftAI/mycroft-skills-kit#49]
This was reported to me by msk:

```
Do you want msk to store the GitHub Personal Access Token? (Y/n) Y
Your GitHub Personal Access Token is stored in /home/.../.mycroft/msk/GITHUB_TOKEN

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/.../'
Created GitHub repo: https://github.com/..../
Created skill at: /opt/mycroft/skills/...

```

But it actually looks like the repo was created without issue. But im not sure if there were more steps or instructions to msk because the logs above say that it failed out. Did it actually fail out? I saw other issues about basic auth being deprecated.

**Comment by krisgesling** [comment]
Interesting, does this happen consistently or just once?

Do you remember which permissions you selected for the [personal access token](https://github.com/settings/tokens/new)? Wondering if it is missing a permission for some non-critical thing.

Could be worth moving `~/.mycroft/msk/GITHUB_TOKEN` and generating a new token to see if the issue is specific to that token.

Also can I confirm which version of MSK you are running? You can get this with:
```
mycroft-pip list | grep msk
```
and so we can reproduce your environment, what OS are you running?

**Comment by JayKayy** [comment]
For personal access token I chose the Repo directory tree.

```
> ./mycroft-pip list | grep msk
msk                           0.3.15    
```
Im running on Fedora 32. I'm also realizing that this is all being done within a container created by `toolbox`. So looking back on it thats probably not how mycroft was intended to be installed.

I was able to replicate it running through it a second time: 

```
Would you like to create a GitHub repo for it? (Y/n) Y

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/JayKayy/test-skill/'
Created GitHub repo: https://github.com/JayKayy/test-skill
Created skill at: /opt/mycroft/skills/test-skill
```

Not sure why its mentioniing username and passwd though.

**Comment by forslund** [comment]
Ok I got this error with three different keys and in my case the reason was... I copied an extra space when I copied the auth key...

In the the github module seem to handle this but the when we do the git commandline calls it fails.

**Comment by forslund** [comment]
I'm going to post a PR to strip any spaces from the key when used, should make it less easy to make a mistake.
